In [ ]:
# tra duong dan, ae doi ten "nam1706" thanh ten kaggle roi copy mang xuong cell duoi
import os
print(os.listdir('/kaggle/input/datasets/nam1706/phy-dataset/'))

['Physics_Problems_Text_Only.csv']

In [13]:
# Import thư viện
import pandas as pd
pd.set_option('display.max_colwidth', None)

# 2. Hiển thị tất cả các cột (nếu có nhiều cột bị ẩn)
pd.set_option('display.max_columns', None)

# 3. Hiển thị tất cả các dòng (cẩn thận nếu file quá lớn)
pd.set_option('display.max_rows', None)
# Đọc file CSV (thay 'ten_file.csv' bằng tên file thực tế của bạn)
df = pd.read_csv('/kaggle/input/datasets/nam1706/phy-dataset/Physics_Problems_Text_Only.csv')



# Kích thước (dòng, cột)
df.shape
# Danh sách tên cột
df.columns.tolist()
# Thống kê mô tả cho cột số
df.describe()

,id,question,cot,answer,unit
count,1755,1754,1753,1354,1340
unique,1755,1752,1747,975,54
top,QA703,"Three identical charges, q = 1.2 × 10^-6 C, are placed at the three vertices of an isosceles right triangle with legs of length 5.2 cm. Calculate the net electric field at the right-angle vertex. Give your answer two decimal places.","Step 1: Analyze circuit conditions\nFrom the condition LCω² = 1 we obtain Z_L = Z_C. This is the phenomenon of full electrical resonance in a series RLC circuit.\nStep 2: Determine the phase difference of the entire circuit\nWhen the circuit is at resonance, the total voltage u_AB and the current i are always in phase with each other. Therefore φ = 0.\nStep 3: Calculate the power factor\nThe power factor of the entire circuit is calculated using cos φ. Since φ = 0 we have cos φ = cos(0) = 1.\nStep 4: Conclusion\nRegardless of the specific values of R₁ and R₂, as long as the resonance condition (Z_L = Z_C) is satisfied, the power factor of the entire circuit always reaches its maximum value. Therefore cos φ = 1.",0,N
freq,1,2,4,18,248

In [17]:

df.head(200)

,id,question,cot,answer,unit
0,TD401,Calculate the energy stored in capacitor C when C = 100 μF and U = 30 V.,"Step 1: Identify the given values for capacitance (C) and voltage (U).\nStep 2: Recall the formula for the energy (E) stored in a capacitor, which is E = 0.5 * C * U^2.\nStep 3: Convert the capacitance to Farads: C = 100 μF = 100 * 10^-6 F = 1 * 10^-4 F.\nStep 4: Substitute the values into the formula: E = 0.5 * (1 * 10^-4 F) * (30 V)^2.",45,J
1,TD402,"Calculate the capacitance C of the capacitor, given that it stores Q = 3 mC when fully charged under U = 30 V.","Step 1: Identify the given values from the question: the charge Q = 3 mC and the voltage U = 30 V.\nStep 2: Recall the formula for capacitance, which is C = Q / U.\nStep 3: Convert the charge to the standard unit (Coulombs): Q = 3 mC = 3 × 10⁻³ C.\nStep 4: Substitute the values into the formula: C = (3 × 10⁻³ C) / (30 V).",100,μF
2,LD001,"Two charges, q1 = 6 × 10^-8 C and q2 = -6 × 10^-8 C, are placed at points A and B in air, 8 cm apart. A third charge, q3 = 6 × 10^-8 C, is placed at point C, with CA = 5 cm and CB = 3 cm. Determine the force acting on q3.","Step 1: Identify the given charges and distances.\nStep 2: Determine the geometric arrangement of points A, B, and C.\nStep 3: Calculate the magnitude of the electrostatic force exerted by q1 on q3 (F13) using Coulomb's Law (F = k * |q1*q2| / r^2), where k = 9 × 10^9 N m^2/C^2.\nStep 4: Determine the direction of F13.",0.05,N
3,LD002,"Three electric charges are placed at three fixed points, forming a right-angled triangle ABC, where AB = 4 m and BC = 5 m. The charges are qA = 5.0 μC, qB = -5.0 μC, and qC = 4.0 μC, respectively. Find the net electric force acting on the charge at A.","Step 1: Identify the charges and distances given in the problem.\nStep 2: The charges are qA = 5.0 μC, qB = -5.0 μC, and qC = 4.0 μC.\nStep 3: The known side lengths of the right-angled triangle are AB = 4 m and BC = 5 m.\nStep 4: To find the net electric force on charge A, we need to calculate the force exerted by B on A (F_BA) and the force exerted by C on A (F_CA) using Coulomb's Law.",24.45 × 10^-3,N
4,LD003,"Points A and B are separated by 20 cm in air. Charges q1 = -3 × 10^-6 C and q2 = 8 × 10^-6 C are placed at A and B, respectively. A test charge q3 = 2 × 10^-6 C is placed at point C such that AC = 12 cm and BC = 16 cm. Calculate the magnitude of the electric force acting on q3.","Step 1: Identify the given charges and distances.\nStep 2: Convert the given distances from centimeters to meters: AC = 0.12 m, BC = 0.16 m, AB = 0.20 m.\nStep 3: Verify the geometry of points A, B, and C. Since AC² + BC² = (0.12 m)² + (0.16 m)² = 0.0144 m² + 0.0256 m² = 0.0400 m², and AB² = (0.20 m)² = 0.0400 m², it implies that AC² + BC² = AB². Therefore, the points form a right-angled triangle at C, meaning angle ACB is 90 degrees.\nStep 4: The formula for the magnitude of the electric force between two point charges is F = k |q1 q2| / r², where k is Coulomb's constant.",6.76,N
5,LD004,"Two point charges q1 = 3 × 10^-8 C and q2 = 2 × 10^-8 C are placed at points A and B in a vacuum, with AB = 5 cm. A charge q0 = -2 × 10^-8 C is placed at M, where MA = 4 cm and MB = 3 cm. Calculate the net electric force acting on q0.","Step 1: Identify the given charges q1 = 3 × 10^-8 C, q2 = 2 × 10^-8 C, and q0 = -2 × 10^-8 C. The distances are MA = 4 cm (0.04 m), MB = 3 cm (0.03 m), and AB = 5 cm (0.05 m). Use Coulomb's constant k = 9 × 10^9 N m^2/C^2.\nStep 2: Verify the geometry of points A, M, and B. Since MA^2 + MB^2 = (4 cm)^2 + (3 cm)^2 = 16 cm^2 + 9 cm^2 = 25 cm^2, and AB^2 = (5 cm)^2 = 25 cm^2, it follows that MA^2 + MB^2 = AB^2. Therefore, triangle AMB is a right-angled triangle with the right angle at M.\nStep 3: Calculate the magnitude of the electric force F10 exerted by q1 on q0 using Coulomb's Law (F = k|q1q0|/r^2).\nStep 4: Determine the direction of F10. Since q1 is positive and q0 is negative, the force F10 is attractive, directed from M towards A.",5.234 × 10^-3,N
6,LD005,"Three electric charges, q1 = q2 = q3 = 1.6 × 10^-19 C, are placed at the three vertices of an equilateral triangle ABC with side length 16 cm in air. Determine the net electric force vector acting on q3.","Step 1: Identify the given values: charges q1 = q2 = q3 = 1.6 × 10^-19 C, and the side length of the equilateral triangle, r = 16 cm.\nStep 2: Convert the side length from centimeters to meters: r = 16 cm = 0.16 m.\nStep 3: State Coulomb's Law, F = k * |q_a * q_b| / r^2, and the value of Coulomb's constant for air, k = 8.9875 × 10^9 N m^2/C^2.\nStep 4: Calculate the magnitude of the individual electrostatic forces. The force exerted by q1 on q3 (F13) and by q2 on q3 (F23) will have the same magnitude since q1=q2 and the distances are equal: F = (8.9875 × 10^9 N m^2/C^2) * (1.6 × 10^-19 C)^2 / (0.16 m)^2 = 8.9875 × 10^-27 N.",9\sqrt{3} × 10^-27,N
7,LD006,"Two point charges q1 = 10^-8 C and q2 = -3×10^-8 C are placed in air at two points A and B, 8 cm apart. A point charge q = 10^-8 C is placed at point M, which is on the perpendicular bisector of the line segment AB and 3 cm away from AB. Given k = 9×10^9 N.m^2/C^2. What is the magnitude of the net electric force exerted by q1 and q2 on q?","Step 1: Convert all given distances to meters and set up a coordinate system. Let the midpoint of AB be the origin (0,0). Then point A is at (-0.04 m, 0) and point B is at (0.04 m, 0). Point M is on the perpendicular bisector, 3 cm away from AB, so M is at (0, 0.03 m).\nStep 2: Calculate the distances from q1 to q (r1) and from q2 to q (r2).\nStep 3: Calculate the magnitude of the electric force F1 exerted by q1 on q using Coulomb's Law, F = k|q1q|/r1^2.\nStep 4: Calculate the magnitude of the electric force F2 exerted by q2 on q using Coulomb's Law, F = k|q2q|/r2^2.",1.23 × 10^-3,N
8,LD007,"Two charges, q1 = +2×10^-6 C and q2 = -2×10^-6 C, are placed at points A and B in a vacuum, 6 cm apart. A third charge, q3 = +2×10^-6 C, is placed on the perpendicular bisector of the line segment AB, 4 cm away from AB. What is the magnitude of the net electric force exerted by q1 and q2 on q3?","Step 1: Identify the given charges and their values: q1 = +2×10^-6 C, q2 = -2×10^-6 C, q3 = +2×10^-6 C.\nStep 2: Determine the positions. The distance between q1 and q2 is 6 cm. q3 is on the perpendicular bisector, 4 cm from the line AB. This forms two right-angled triangles with legs 3 cm (half of 6 cm) and 4 cm.\nStep 3: Calculate the distance from q1 to q3 (r13) and q2 to q3 (r23). Using the Pythagorean theorem, r = sqrt((3 cm)^2 + (4 cm)^2) = sqrt(9 + 16) = sqrt(25) = 5 cm = 0.05 m. So, r13 = r23 = 0.05 m.\nStep 4: Calculate the magnitude of the electric force F13 exerted by q1 on q3 using Coulomb's Law (F = k * |q1 * q3| / r^2, where k = 9×10^9 N m^2/C^2). F13 = (9×10^9 N m^2/C^2) * |(+2×10^-6 C) * (+2×10^-6 C)| / (0.05 m)^2 = (9×10^9 * 4×10^-12) / 0.0025 = (36×10^-3) / (2.5×10^-3) = 14.4 N.",17.28,N
9,LD008,"Two electric forces are acting in the same direction, with magnitudes of 3 N and 4 N respectively. What is the resultant force?","Step 1: Identify the magnitudes of the two forces given in the problem.\nStep 2: Note that the problem states both forces are acting in the same direction.\nStep 3: To find the resultant force of multiple forces acting in the same direction, add their magnitudes.\nStep 4: Calculate the resultant force by adding the given magnitudes: 3 N + 4 N.",7,N
10,LD009,"Two electric forces, each with a magnitude of 5 N, act at an angle of 60° to each other. What is the resultant force?",Step 1: The magnitudes of the two electric forces are F1 = 5 N and F2 = 5 N.\nStep 2: The angle between the two forces is θ = 60°.\nStep 3: The formula for the resultant force (R) of two forces F1 and F2 with an angle θ between them is R = √(F1² + F2² + 2F1F2cosθ).\nStep 4: Substitute the given values into the formula: R = √(5² + 5² + 2 * 5 * 5 * cos(60°)).,8.66,N
11,LD010,"Three charges q1 = +2 μC, q2 = +2 μC, and q3 = -2 μC are placed at the three vertices of an equilateral triangle with a side length of 10 cm. Calculate the magnitude of the net electric force acting on q3.","Step 1: Identify the given charges and the side length of the equilateral triangle.\nStep 2: State Coulomb's Law, F = k * |q1 * q2| / r^2, where k is Coulomb's constant (approximately 8.9875 * 10^9 N m^2/C^2).\nStep 3: Calculate the magnitude of the attractive force F31 exerted by q1 on q3: F31 = (8.9875 * 10^9 N m^2/C^2) * |(2 * 10^-6 C) * (-2 * 10^-6 C)| / (0.10 m)^2 = 35.95 N.\nStep 4: Calculate the magnitude of the attractive force F32 exerted by q2 on q3: F32 = (8.9875 * 10^9 N m^2/C^2) * |(2 * 10^-6 C) * (-2 * 10^-6 C)| / (0.10 m)^2 = 35.95 N.",6.24,N
12,LD011,"An electric charge is subjected to two electric forces with magnitudes of 4 N and 3 N, acting at an angle of 90° to each other. Calculate the resultant force. (This is a very direct and clear translation.)","Step 1: Identify the magnitudes of the two electric forces and the angle between them.\nStep 2: Force 1 (F1) has a magnitude of 4 N.\nStep 3: Force 2 (F2) has a magnitude of 3 N.\nStep 4: The forces act at an angle of 90° to each other, meaning they are perpendicular.",5,N
13,LD012,"Three charges q1 = +1 μC, q2 = +1 μC, and q3 = -1 μC are placed at the vertices of an equilateral triangle with side a = 20 cm. Calculate the magnitude of the net force acting on q3.","Step 1: Identify the given charges and the side length of the equilateral triangle.\nStep 2: Convert the given values into SI units: q1 = +1 × 10⁻⁶ C, q2 = +1 × 10⁻⁶ C, q3 = -1 × 10⁻⁶ C, and a = 0.20 m.\nStep 3: Calculate the magnitude of the electrostatic force exerted by q1 on q3 (F13) using Coulomb's Law, F = k |q1q3|/r², where k = 9 × 10⁹ N m²/C².\nStep 4: F13 = (9 × 10⁹ N m²/C²) × (1 × 10⁻⁶ C) × (1 × 10⁻⁶ C) / (0.20 m)² = 0.225 N.",0.39,N
14,LD013,"Two charges are placed equidistant from point O. The electric forces exerted by these two charges on point O are 6 N and 8 N, respectively, and are perpendicular to each other. Calculate the resultant force at O.","Step 1: Identify the magnitudes of the two electric forces acting on point O.\nStep 2: The first force is 6 N and the second force is 8 N.\nStep 3: Identify that the two forces are perpendicular to each other.\nStep 4: To find the resultant force of two perpendicular forces, use the Pythagorean theorem: Resultant Force = $\sqrt{(\text{Force 1})^2 + (\text{Force 2})^2}$.",10,N
15,LD014,"Two charges separated by 15 cm exert a force of 4.8 N. Given that q1 = q2 = q, find q.","Step 1: Identify the given values from the question: The force (F) between the charges is 4.8 N, the separation distance (r) is 15 cm, and the magnitudes of the charges are equal (q1 = q2 = q).\nStep 2: State Coulomb's Law, which describes the magnitude of the electrostatic force between two point charges: F = k * |q1 * q2| / r^2, where k is Coulomb's constant (approximately 9 x 10^9 N m^2/C^2).\nStep 3: Convert the separation distance from centimeters to meters: r = 15 cm = 0.15 m.\nStep 4: Substitute the given values (F = 4.8 N, r = 0.15 m, k = 9 x 10^9 N m^2/C^2) and the condition q1 = q2 = q into Coulomb's Law: 4.8 = (9 x 10^9) * q^2 / (0.15)^2.",3.46,μC
16,LD015,Two electric forces with magnitudes of 5 N and 12 N act at an angle of 60° to each other. Calculate the resultant force.,Step 1: Identify the magnitudes of the two electric forces as 5 N and 12 N.\nStep 2: Identify the angle between the two forces as 60°.\nStep 3: Use the formula for the resultant force: R = sqrt(F1^2 + F2^2 + 2 * F1 * F2 * cos(theta)).\nStep 4: Substitute the given values: R = sqrt(5^2 + 12^2 + 2 * 5 * 12 * cos(60°)).,15.13,N
17,LD016,"Three identical charges q = +1 μC are placed at the three vertices of an isosceles right triangle, with sides of length a = 10 cm. Calculate the net force acting on the charge at the right angle vertex.","Step 1: Identify the given values: charges q = +1 x 10^-6 C, leg length a = 0.10 m, and Coulomb's constant k = 8.9875 x 10^9 N m^2/C^2.\nStep 2: Recognize that the charge at the right angle vertex (let's call it C) experiences two forces: one from each of the other two charges (let's call them A and B).\nStep 3: Calculate the magnitude of the force F_AC exerted by charge A on charge C using Coulomb's Law: F = k * q^2 / r^2.\nStep 4: Since charges A and B are identical and equidistant from C (r=a), the force F_BC exerted by charge B on charge C has the same magnitude: F_BC = 0.89875 N.",1.27,N
18,LD017,"Three charges: q1 = +3 μC, q2 = -2 μC, and q3 = +1 μC are placed 10 cm apart on a straight line. Calculate the force acting on q2.",Step 1: Identify the given values for charges and distances.\nStep 2: Calculate the force exerted by q1 on q2 (F12).\nStep 3: Determine the magnitude of F12.\nStep 4: Calculate the force exerted by q3 on q2 (F32).,3.6,N
19,LD018,Two identical charges q = +2 μC are placed at two vertices of an equilateral triangle with side length a = 0.1 m. A charge q′ = -1 μC is placed at the remaining vertex. Calculate the net electric force acting on q′.,"Step 1: Identify the given values for charges, side length, and Coulomb's constant.\nStep 2: Calculate the magnitude of the electric force (F) exerted by one of the charges 'q' on 'q'' using Coulomb's Law: F = k * |q * q'| / a^2.\nStep 3: Substitute the given values (k = 8.9875 x 10^9 N m^2/C^2, q = 2 x 10^-6 C, q' = -1 x 10^-6 C, a = 0.1 m) into the formula.\nStep 4: Determine the directions of the two forces acting on q'. Since q is positive and q' is negative, both forces are attractive, pointing from q' towards each of the 'q' charges.",3.12,N
20,LD019,"Two electric forces have magnitudes of 6 N and 8 N, acting at an angle of 120° to each other. Calculate the resultant force of these two forces.","Step 1: Identify the given magnitudes of the two electric forces and the angle between them.\nStep 2: The formula for the resultant force (R) of two forces (F1 and F2) acting at an angle (θ) is R² = F1² + F2² + 2F1F2 cos(θ).\nStep 3: Substitute the given values: F1 = 6 N, F2 = 8 N, and θ = 120° into the formula.\nStep 4: Calculate R² = (6 N)² + (8 N)² + 2(6 N)(8 N) cos(120°).",7.21,N
21,LD020,"A charge is acted upon by two forces, each of magnitude 10 N. Find the angle between the two forces if the resultant force is also 10 N.","Step 1: Identify the magnitudes of the two forces (F1, F2) and the resultant force (R).\nStep 2: F1 = 10 N, F2 = 10 N, R = 10 N.\nStep 3: Use the formula for the resultant of two forces: R² = F₁² + F₂² + 2F₁F₂cosθ.\nStep 4: Substitute the given values into the formula: 10² = 10² + 10² + 2(10)(10)cosθ.",120,Độ
22,LD021,"A charge q = -1 μC is attracted by two +1 μC charges. These two positive charges are located on opposite sides of q, along the same straight line passing through q, at distances of 5 cm and 12 cm respectively from q.","Step 1: Identify the charges: A central charge q = -1 μC, and two positive charges, Q1 = +1 μC and Q2 = +1 μC.\nStep 2: Note their arrangement: The two positive charges are on opposite sides of q, along a straight line.\nStep 3: Identify the distances: The distance from q to one positive charge is r1 = 5 cm, and to the other is r2 = 12 cm.\nStep 4: The problem statement describes a physical setup but does not explicitly ask a question to be solved (e.g., Calculate the net force on q, or Find the electric potential at q).",2.98,N
23,LD022,"Two electric charges, q1 = +2 μC and q2 = -2 μC, are placed 10 cm apart. A charge q3 = +1 μC is placed at the midpoint of the line segment connecting q1 and q2. Calculate the net force acting on q3.","Step 1: Identify the given charges and the total distance between q1 and q2.\nStep 2: Determine the distance from q1 to q3 (r13) and from q2 to q3 (r23), since q3 is at the midpoint.\nStep 3: Calculate the magnitude of the force F13 exerted by q1 on q3 using Coulomb's Law (F = k * |q1*q3| / r13^2), where k = 9 * 10^9 N m^2/C^2.\nStep 4: Determine the direction of F13. Since q1 (+2 μC) and q3 (+1 μC) are both positive, the force is repulsive, directed away from q1 towards q2.",14.4,N
24,LD023,"Two forces act on a charge. They are collinear and act in opposite directions, with magnitudes of 15 N and 9 N. Calculate the magnitude and direction of the resultant force.","Step 1: The problem states two forces are collinear and act in opposite directions.\nStep 2: To find the magnitude of the resultant force when two forces act in opposite directions, subtract the smaller magnitude from the larger magnitude.\nStep 3: Calculate the magnitude: 15 N9 N = 6 N.\nStep 4: The direction of the resultant force is the same as the direction of the force with the larger magnitude.",6,N
25,LD024,"Three charges q1 = +1 μC, q2 = -2 μC, q3 = +3 μC are placed at the vertices of an isosceles right triangle with legs of 0.1 m. Calculate the net force acting on q3.","Step 1: Identify the given charges and their values: q1 = +1 μC, q2 = -2 μC, q3 = +3 μC.\nStep 2: Identify the geometric shape as an isosceles right triangle with legs of 0.1 m.\nStep 3: Recognize that the question does not specify the placement of q1, q2, and q3 at the vertices of the triangle.\nStep 4: To calculate the net force on q3, the specific positions of q1 and q2 relative to q3 are required. This determines the distances and angles between the charges.",06.04,N
26,LD025,"Two charges, q1 = +2 μC and q2 = +2 μC, are placed at the ends of a 10 cm long line segment. A third charge, q3 = -1 μC, is positioned along the line connecting q1 and q2. Calculate the net force acting on q3 when it is 4 cm away from q1.","Step 1: Identify the given charges and distances, converting them to SI units, and state Coulomb's constant (k).\nStep 2: Determine the distance between charge q3 and charge q2.\nStep 3: Calculate the magnitude of the electrostatic force exerted by q1 on q3 (F13) using Coulomb's Law (F = k * |q1*q3| / r^2).\nStep 4: Determine the direction of the force F13.",6.25,N
27,LD026,"Two electric charges, q1 = 8 × 10^-8 C and q2 = -8 × 10^-8 C, are placed at points A and B respectively, in air (AB = 6 cm). Determine the force acting on a third charge q3 = 8 × 10^-8 C, given that: CA = 4 cm and CB = 2 cm.","Step 1: Identify the given charges (q1 = 8 × 10^-8 C, q2 = -8 × 10^-8 C, q3 = 8 × 10^-8 C) and distances (CA = 4 cm = 0.04 m, CB = 2 cm = 0.02 m). The Coulomb's constant for air is k = 9 × 10^9 N m²/C².\nStep 2: Determine the geometric arrangement: Since CA + CB = 4 cm + 2 cm = 6 cm, which equals the distance AB = 6 cm, point C lies directly between points A and B.\nStep 3: Calculate the magnitude of the force F13 exerted by q1 on q3 using Coulomb's Law: F13 = k * |q1 * q3| / CA² = (9 × 10^9 N m²/C²) * (8 × 10^-8 C * 8 × 10^-8 C) / (0.04 m)² = 0.036 N.\nStep 4: Determine the direction of F13: Since q1 and q3 are both positive, F13 is repulsive, meaning it pushes q3 away from q1 (point A). As C is between A and B, F13 points towards B.",0.18,N
28,LD027,"Two charges, q1 = 8×10^-8 C and q2 = -8×10^-8 C, are placed at points A and B in the air (AB = 6 cm). Determine the force acting on a third charge q3 = 8×10^-8 C, if CA = 4 cm and CB = 10 cm.","Step 1: Establish the relative positions of points A, B, and C based on the given distances.\nStep 2: Calculate the magnitude and direction of the force F13 exerted by q1 on q3.\nStep 3: Calculate the magnitude and direction of the force F23 exerted by q2 on q3.\nStep 4: Determine the net force on q3 by vectorially adding F13 and F23.",30.24 × 10^-3,N